Fix test_padded_moe_reload_releases_each_layer tests fail due to AttributeError: 'UnquantizedFusedMoEMethod' object has no attribute 'unquantized_backend'
Signed-off-by: Sergei Shliapnikov <sergei.shliapnikov@amd.com>