Try multiproc in test
To fix the test I switched to uniproc processor, but
now I'm getting weird issues like

```
torch._dynamo.exc.BackendCompilerFailed: backend='<vllm.compilation.backends.VllmBackend object at 0x7ef9f68ca600>' raised:
AttributeError: module 'torch._tensor' has no attribute 'split'
```

Signed-off-by: Max de Bayser <mbayser@br.ibm.com>