Fix unknown attribute of topk_indices_dtype in CompressedTensorsW8A8Fp8MoECutlassMethod (#20507)
Summary:
Pull Request resolved: https://github.com/vllm-project/vllm/pull/20507

Fix Error
```
RuntimeError: Worker failed with error ''CompressedTensorsW8A8Fp8MoECutlassMethod' object has no attribute 'topk_indices_dtype'', please check the stack trace above for the root cause
```
{F1980046154}

Test Plan:
https://www.internalfb.com/vanguard/serving_test_cases/2171707933255590

Rollback Plan:

Differential Revision: D77808053