[Core] Async scheduling: Handle model forward errors more cleanly
If the model runner execute_model() raises an exception, it will be logged via a future callback, but the core loop will subsequently fail with a misleading exception since sample_tokens() will return None:

`AttributeError: 'NoneType' object has no attribute 'sampled_token_ids'`

This PR changes the step_with_batch_queue() method to instead raise the root cause exception from the execute_model() future inline in this case, which also removes the need for the error callback.

Signed-off-by: njhill <nickhill123@gmail.com>