v1: MPClient.proc-handle can be None
Fixes:

vllm/v1/engine/core_client.py:196: error: Incompatible types in assignment (expression has type "None", variable has type "EngineCoreProcHandle")  [assignment]

Signed-off-by: Mark McLoughlin <markmc@redhat.com>