Enable support for aiter_w8a8_block_fp8_linear in MI300 and MI350 series
- Note that the `is_fp8_fnuz` condition should only be used to check for the
  FP8 format, not as a generic check for MI300 platform.
- Register the aiter JIT:ed op using direct_register_custom_op, to prevent dynamo from trying to compile it.
- Avoid using functools.partial, because direct_register_custom_op attempts to infer schema, leading to
    AttributeError: 'functools.partial' object has no attribute '__globals__'
- Rename aiter_per1x128_quant to rocm_aiter_per1x128_quant for consistency
- Rename kernel selection check to use_aiter_fp8_linear.
  The function checks whether FP8 is both supported and enabled by env flags.
  Renaming from check_aiter_fp8_linear_support to use_aiter_fp8_linear,
  in order to distinguish from current_platform.supports_aiter_w8a8_block_fp8_linear
  which only checks for support but does not check the env flags.
- Remove duplication between architecture check methods.
  There was code duplication between use_custom_allreduce and the newly added
  supports_aiter_w8a8_block_fp8_linear. Both methods perform the same check for
  MI300/MI350 series GPUs. To improve maintainability and avoid potential
  inconsistencies in the future, this logic was extracted into a shared
  private helper method `arch_is_in`.
  The helper method was applied to the other architecture checks of the same form.
  Thanks @gemini-code-assist for the suggestion!

Signed-off-by: Stig-Arne Grönroos <stig-arne.gronroos@amd.com>