Update model-hosting-container-standards to 0.1.10
https://pypi.org/project/model-hosting-container-standards/0.1.10/
This release disables the need to create sagemaker_sessions folder by default, potentially causing an error in the vLLM container
```
PermissionError: [Errno 13] Permission denied: '/dev/shm/sagemaker_sessions'
```


Signed-off-by: Michael Goin <mgoin64@gmail.com>