Fix mypy error from CI gate
Errors from following cmd:

$ pre-commit run -a --hook-stage manual mypy-3.10
Run mypy for Python 3.10.................................................Failed
- hook id: mypy-3.10
- exit code: 1

$ mypy --python-version 3.10
vllm/config/kv_events.py:21: error: Argument "default" to "Field" has incompatible type "None"; expected "Literal['null', 'zmq']"  [arg-type]
vllm/config/kernel.py:29: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/model.py:143: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
vllm/config/model.py:199: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
vllm/config/compilation.py:119: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:121: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:123: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:127: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:131: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:133: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:139: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:141: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:408: error: Incompatible types in assignment (expression has type "None", variable has type "CompilationMode")  [assignment]
vllm/config/compilation.py:526: error: Incompatible types in assignment (expression has type "None", variable has type "CUDAGraphMode")  [assignment]
vllm/config/compilation.py:588: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
vllm/config/compilation.py:751: error: Argument "exclude" to "dump_python" of "TypeAdapter" has incompatible type "dict[str, object]"; expected "set[int] | set[str] | Mapping[int, IncEx | bool] | Mapping[str, IncEx | bool] | None"  [arg-type]
vllm/config/vllm.py:254: error: Incompatible types in assignment (expression has type "None", variable has type "ModelConfig")  [assignment]
vllm/config/speculative.py:69: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
vllm/config/speculative.py:366: error: Incompatible types in assignment (expression has type "str | None", variable has type "Literal['awq', 'fp8', 'ptpc_fp8', 'fbgemm_fp8', 'fp_quant', 'modelopt', 'modelopt_fp4', 'modelopt_mxfp8', 'modelopt_mixed', 'gguf', 'gptq_marlin', 'awq_marlin', 'gptq', 'compressed-tensors', 'bitsandbytes', 'experts_int8', 'quark', 'moe_wna16', 'torchao', 'inc', 'mxfp4', 'petit_nvfp4', 'cpu_awq'] | None")  [assignment]
Found 19 errors in 6 files (checked 761 source files)

There was also an additional error caused by the fixes to the errors abovee:
vllm/engine/arg_utils.py:1884: error: Argument "offload_backend" to "OffloadConfig" has incompatible type "str"; expected "Literal['auto', 'uva', 'prefetch']"  [arg-type]

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>