v1: fix block_hash mypy errors
BlockHashType token IDs should be Tuple[int, ...] - it's not just
one int.

Also, pass the token IDs as a Sequence[int] and convert to a tuple
only when we need it in hash_block_tokens().

Make ConstantList a Sequence subclass to allow this.

Fixes:

vllm/v1/core/kv_cache_utils.py:206: error: Argument 2 to "hash_block_tokens" has incompatible type "tuple[int, ...]"; expected "tuple[int]"  [arg-type]
vllm/v1/core/kv_cache_manager.py:89: error: Argument 2 to "hash_request_tokens" has incompatible type "ConstantList[int]"; expected "list[int]"  [arg-type]
vllm/v1/core/kv_cache_manager.py:401: error: Argument 2 to "hash_block_tokens" has incompatible type "tuple[int, ...]"; expected "tuple[int]"  [arg-type]

Signed-off-by: Mark McLoughlin <markmc@redhat.com>