[BugFix] Add triton lang placeholder for exp2
Fixes `AttributeError: module 'triton.language' has no attribute 'exp2``
observed when running GDN models on platforms that don't support triton.
This was introduced by: https://github.com/vllm-project/vllm/pull/43195

Signed-off-by: Fadi Arafeh <fadi.arafeh@arm.com>