[V1][Spec Decode] Fix eagle3 parameter definition
The redundant .type(torch.LongTensor) moves the GPU tensor to CPU
causing:

```
    targets = base + self.draft_id_to_target_id
              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Signed-off-by: Mark McLoughlin <markmc@redhat.com>