Fix: Correct FusedMoE layer reference in auto_round quantization
- Changed `layer.moe` to `layer` in AWQ MoE method
- Changed `layer.moe` to `layer` in GPTQ MoE method
- FusedMoE object doesn't have .moe attribute, should use layer directly

This fixes AttributeError: 'FusedMoE' object has no attribute 'moe'
when using "auto_round" quantization with FusedMoE layers."

Signed-off-by: David-Wen <18927700430@163.com>