[DeepSeekV3.2] Fix Loading BF16 weights
Thrown load weight error when infer with BF16 weights of DeepSeekV3.2-EXP (converted from FP8 weigiths on hugging face).

```log
ValueError: Following weights were not initialized from checkpoint: {'model.layers.2.self_attn.indexer.weights_proj.bias', 'model.layers.4.self_attn.indexer.weights_proj.bias', 'model.layers.1.self_attn.indexer.weights_proj.bias', 'model.layers.5.self_attn.indexer.weights_proj.bias', 'model.layers.3.self_attn.indexer.weights_proj.bias', 'model.layers.0.self_attn.indexer.weights_proj.bias'}
... ...
```

Fix weights_proj with bias=False, then BF16 weights can work.

Signed-off-by: Qi Li <qili93@qq.com>