[BugFix] Ensure num_cached_tokens is non-negative for kv transfer failed requests
For requests failing KV load in decode side, since it's still in WAITING_REMOTE_KV state, its num_cached_tokens are still the  default -1, and it was never updated, when we do metrics logging on local_cache_hit, -1 will be used and will crash engine due to:

ValueError: Counters can only be incremented by non-negative amounts.