disable tool server initialization if no tool in request
Summary:
First part of fixing https://github.com/vllm-project/vllm/issues/25697

we can first fix this error
```
RuntimeError: Attempted to exit cancel scope in a different task than it was entered in
```
by not initializing the tool servers if the request doesn't need tools.

Test Plan:
- non stream request with tools still gets tools
- stream without tools no longer outputs the error
- stream with tools still works (but it still outputs the error)

Differential Revision: D83387320

Signed-off-by: Andrew Xia <axia@meta.com>