Optimize triton unified attention performance for sliding window attention (#24390)
Summary:

Signed-off-by: Zixi Qi <qizixi@meta.com>

Optimize kernel_unified_attention_2d attention performance for sliding window attention by pruning unused tiles  

Before this change, GPT-OSS + triton attention backend was spending equal amount of time between global and local attention due to attn score still calculated by masked out sequences
{F1981789247, width=300}

After this change, sliding window attention become much cheaper
{F1981789250, width=300}

Test Plan:
GPT-OSS 120b eval with this change
```
Writing report to /tmp/aime25_gpt-oss-120b-medium_temp1.0_20250906_171957.html
{'chars': 2580.5666666666666, 'chars:std': 1246.4907456090032, 'score': 0.875, 'score:std': 0.33071891388307384}
Writing results to /tmp/aime25_gpt-oss-120b-medium_temp1.0_20250906_171957.json
Writing all results to /tmp/aime25_gpt-oss-120b-medium_temp1.0_20250906_171957_allresults.json
[{'eval_name': 'aime25', 'model_name': 'gpt-oss-120b-medium_temp1.0_20250906_171957', 'metric': 0.875}]
```

Unit tests pass
```
pytest -v tests/kernels/attention/test_triton_unified_attention.py

==================================================================================================================== warnings summary ====================================================================================================================
../uv_env/vllm/lib64/python3.12/site-packages/schemathesis/generation/coverage.py:305
  /home/qizixi/uv_env/vllm/lib64/python3.12/site-packages/schemathesis/generation/coverage.py:305: DeprecationWarning: jsonschema.exceptions.RefResolutionError is deprecated as of version 4.18.0. If you wish to catch potential reference resolution errors, directly catch referencing.exceptions.Unresolvable.
    ref_error: type[Exception] = jsonschema.RefResolutionError,

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================================================= 64 passed, 64 skipped, 1 warning in 53.32s =======================================================================================================
```

Rollback Plan:

Differential Revision: D81865757