Upgrade neuron to 2.20.2
This change also fixed loading Neuron models. Neuron uses old pytorch,
 before the change I was getting

TypeError: infer_schema() takes 1 positional argument but 2 were given

which was caused by custom_op direct registration. I'm disabling that
if custom_op is not available.

Signed-off-by: Jerzy Zagorski <jzagorsk@amazon.com>