[API Server] arguments already have defaults, should always be present
There's no reason to use getattr() or repeat the default values for
args, since they will always be present with the default specified
in their declaration.

Fixes:

```
File "/home/markmc/vllm-project/vllm/vllm/entrypoints/openai/cli_args.py", line 338, in validate_parsed_serve_args
  if getattr(args, "api_server_count", 1) > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Signed-off-by: Mark McLoughlin <markmc@redhat.com>