[XPU] Use spawn with XPU multiprocessing
It's required to use `spawn` start method running XPU backend with
multiprocessing. There are 2 places in vllm where this needs to be
fixed:
* One in `vllm/utils`
* Another in `test/utils`

Fix in the test adjusts `create_new_process_for_each_test` decorator
which further needs to be used for the actual test. Some tests are
already marked with it due to work done for ROCm. In some cases it
might still be missing or `fork_new_process_for_each_test` used instead.

This commit unlocks running a number of tests on xpu and allows tolook
into actual runtime issues. Commit behavior can be tried on these tests:
* `tests/v1/engine/test_llm_engine.py::test_engine_metrics`
* `tests/v1/e2e/test_cascade_attention.py`

Error happenning before the fix:
```
RuntimeError: Cannot re-initialize XPU in forked subprocess. To use XPU with multiprocessing, you must use the 'spawn' start method
```

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>