[Misc] fixed nvfp4_moe test failures due to invalid kwargs
This seems to be an easy fix.

cutlass_moe_fp4 takes g1_alphas and g2_alphas instead of
w1_alphas and w2_alphas:

https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/fused_moe/cutlass_moe.py#L686-L687

before the fix:

```
$ pytest tests/kernels/moe/test_nvfp4_moe.py -k test_cutlass_fp4_moe_no_graph[dtype1-8-256-224-1024-1536]
...
TypeError: cutlass_moe_fp4() got an unexpected keyword argument 'w1_alphas'
```

after the fix:
```
$ pytest tests/kernels/moe/test_nvfp4_moe.py -k test_cutlass_fp4_moe_no_graph[dtype1-8-256-224-1024-1536]
...
1 passed, 179 deselected, 2 warnings in 3.75s
```

Signed-off-by: Yang Chen <yangche@fb.com>