[Fix] Improve error handling for weight initialization in UnquantizedLinearMethod and Attention class. When initializing vLLM the `torch.OutOfMemoryError: CUDA out of memory.` is opaque and does not indicate which step of the loading model it failed. Also it is not clear where the pre-allocated memory has been used.
Errors like:
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB. GPU 2 has a total capacity of 23.57 GiB of which 235.88 MiB is free. Including non-PyTorch memory, this process has 23.33 GiB memory in use. Of the allocated memory 23.03 GiB is allocated by PyTorch, and 13.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
This small change will include a more clear error message on which step of the model loading the error has occured and allow users to change the settings to use a model that will fit the memory or adjust other settings in the vllm.

Signed-off-by: Rafael Marcelino Koike <rafael.koike@oracle.com>
Signed-off-by: Rafael Koike <koike.rafael@gmail.com>